[package]
name = "cclover-desktop"
version = "0.1.0"
edition = "2024"

[dependencies]
cclover-core = { path = "../cclover-core" }
cclover-desktop-ui = { path = "../cclover-desktop-ui" }
cclover-presentation = { path = "../cclover-presentation" }
iced = { version = "0.14.0", default-features = false, features = ["canvas", "crisp", "smol", "wgpu", "wayland", "x11"] }
smol = "2.0"

[target.'cfg(target_os = "linux")'.dependencies]
iced_layershell = "0.19.1"
ksni = { version = "0.3.6", default-features = false, features = ["async-io", "blocking"] }
x11rb = { version = "0.13.2", features = ["shape"] }
winit-common = "=0.31.0-beta.2"
winit-core = "=0.31.0-beta.2"
