[package]
name = "cclover-desktop"
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-or-later"
build = "build.rs"

[dependencies]
cclover-core = { path = "../cclover-core" }
cclover-presentation = { path = "../cclover-presentation" }
cclover-ui = { path = "../cclover-ui" }
crossbeam-channel = "0.5"

[build-dependencies]
cc = "1"
pkg-config = "0.3"
