[package]
name = "cclover-http"
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-or-later"

[dependencies]
cclover-core = { path = "../cclover-core" }
cclover-presentation = { path = "../cclover-presentation" }
cclover-ui = { path = "../cclover-ui" }
cclover-web-ui = { path = "../cclover-web-ui" }
cclover-runtime = { path = "../cclover-runtime" }
crossbeam-channel = "0.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
